# Generated by Django 5.1.7 on 2025-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presentation',
            field=models.TextField(blank=True, null=True, verbose_name='Présentation'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil'),
        ),
    ]
